<a href="https://colab.research.google.com/github/adigun3/Getting-and-Cleaning-Data/blob/master/Femi_Training_set_decision_tree_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
dataset = pd.read_csv('Femi_training_set_business_nocity_500.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  33.604054   -112.105933  ]
 [  33.4605258  -112.0739333 ]
 [  33.3922099  -112.0853773 ]
 [  33.712797   -112.200264  ]
 [  33.60776606 -112.4816322 ]
 [  33.5096582  -112.0987501 ]
 [  33.551903   -112.132866  ]
 [  33.492195   -111.9312992 ]
 [  33.3788385  -111.8120071 ]
 [  33.5135194  -111.8887889 ]
 [  33.480105   -112.0813612 ]
 [  33.468815   -112.3920218 ]
 [  33.6174589  -111.926272  ]
 [  33.3054266  -111.9032256 ]
 [  33.5993236  -111.9820907 ]
 [  33.3503     -111.931256  ]
 [  33.566989   -112.116243  ]
 [  33.317906   -111.964138  ]
 [  33.8242305  -111.9229042 ]
 [  33.519545   -111.5468301 ]
 [  33.49447    -111.924226  ]
 [  33.5803589  -112.120516  ]
 [  33.581867   -111.881625  ]
 [  33.7801176  -111.9257696 ]
 [  33.624638   -111.930343  ]
 [  33.5388471  -111.9641728 ]
 [  33.65708467 -112.1795726 ]
 [  33.285218   -111.71703   ]
 [  33.4661264  -111.9175425 ]
 [  33.4076118  -111.9470154 ]
 [  32.9482948  -112.7113217 ]
 [  33.503223   -112.065449  ]
 [  33.6

In [4]:
print(y)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False  True  True
  True False  True  True  True  True  True False False  True  True  True
  True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False  True  True
  True  True  True False  True  True False  True  True  True  True  True
  True  True False  True  True  True  True  True  T

## Taking care of missing data

In [0]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[[  33.604054   -112.105933  ]
 [  33.4605258  -112.0739333 ]
 [  33.3922099  -112.0853773 ]
 [  33.712797   -112.200264  ]
 [  33.60776606 -112.4816322 ]
 [  33.5096582  -112.0987501 ]
 [  33.551903   -112.132866  ]
 [  33.492195   -111.9312992 ]
 [  33.3788385  -111.8120071 ]
 [  33.5135194  -111.8887889 ]
 [  33.480105   -112.0813612 ]
 [  33.468815   -112.3920218 ]
 [  33.6174589  -111.926272  ]
 [  33.3054266  -111.9032256 ]
 [  33.5993236  -111.9820907 ]
 [  33.3503     -111.931256  ]
 [  33.566989   -112.116243  ]
 [  33.317906   -111.964138  ]
 [  33.8242305  -111.9229042 ]
 [  33.519545   -111.5468301 ]
 [  33.49447    -111.924226  ]
 [  33.5803589  -112.120516  ]
 [  33.581867   -111.881625  ]
 [  33.7801176  -111.9257696 ]
 [  33.624638   -111.930343  ]
 [  33.5388471  -111.9641728 ]
 [  33.65708467 -112.1795726 ]
 [  33.285218   -111.71703   ]
 [  33.4661264  -111.9175425 ]
 [  33.4076118  -111.9470154 ]
 [  32.9482948  -112.7113217 ]
 [  33.503223   -112.065449  ]
 [  33.6

## Encoding categorical data

### Encoding the Independent Variable

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)

[[0.0 1.0 0.0 33.604054 -112.10593300000001]
 [0.0 1.0 0.0 33.460525800000006 -112.0739333]
 [0.0 1.0 0.0 33.3922099 -112.0853773]
 [1.0 0.0 0.0 33.712796999999995 -112.20026399999999]
 [1.0 0.0 0.0 33.60776606 -112.48163219999999]
 [0.0 1.0 0.0 33.5096582 -112.09875009999999]
 [0.0 0.0 1.0 33.49447 -111.924226]
 [0.0 1.0 0.0 33.5803589 -112.120516]
 [0.0 0.0 1.0 33.538847100000005 -111.96417279999999]
 [1.0 0.0 0.0 33.65708467 -112.1795726]]


### Encoding the Dependent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0
 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [10]:
print(X_train)

[[  33.488414   -112.082007  ]
 [  33.6548815  -112.1337928 ]
 [  33.640021   -112.078594  ]
 [  33.6106566  -112.1505433 ]
 [  33.5087368  -111.9953195 ]
 [  33.4796348  -111.9093213 ]
 [  33.5517332  -112.2692793 ]
 [  33.625322   -111.977313  ]
 [  33.3209897  -111.7898954 ]
 [  33.4382789  -112.0178286 ]
 [  33.3921848  -112.1250269 ]
 [  33.506201   -112.0739253 ]
 [  33.4492269  -112.0951787 ]
 [  33.4470956  -111.9259877 ]
 [  33.5675237  -112.1371293 ]
 [  33.3634762  -111.9112224 ]
 [  33.5095361  -112.085784  ]
 [  33.8242305  -111.9229042 ]
 [  33.64243764 -112.2252989 ]
 [  33.3776903  -111.7528848 ]
 [  33.4224084  -111.8644947 ]
 [  33.597474   -112.119087  ]
 [  33.5384488  -112.1542252 ]
 [  33.343721   -112.521877  ]
 [  33.655418   -112.153592  ]
 [  33.6628743  -112.1866608 ]
 [  33.6048477  -112.0366617 ]
 [  33.5802421  -111.9258314 ]
 [  33.3344463  -111.8463705 ]
 [  33.503323   -111.9284569 ]
 [  33.3928693  -111.9388891 ]
 [  33.4423368  -112.0657857 ]
 [  33.3

In [11]:
print(X_test)

[[  33.6390345  -111.9817311 ]
 [  33.516352   -112.341109  ]
 [  33.6378053  -112.1528218 ]
 [  33.6384243  -112.1925299 ]
 [  33.639971   -112.029015  ]
 [  33.378124   -112.068671  ]
 [  33.6397206  -112.1185603 ]
 [  33.503223   -112.065449  ]
 [  33.742499   -111.977509  ]
 [  33.347289   -111.961862  ]
 [  33.2500293  -111.8376446 ]
 [  33.3912468  -111.9089862 ]
 [  33.499735   -111.9235067 ]
 [  33.6402102  -112.0663313 ]
 [  33.4738952  -112.0649195 ]
 [  32.8786089  -111.7157877 ]
 [  33.3490842  -111.9449183 ]
 [  33.4806776  -112.1091081 ]
 [  33.7084086  -112.272659  ]
 [  33.5108735  -112.134201  ]
 [  33.3785219  -111.9286939 ]
 [  33.498028   -111.927951  ]
 [  33.4634252  -112.3584488 ]
 [  33.3004279  -111.8419    ]
 [  33.394763   -111.908919  ]
 [  33.5276319  -112.064644  ]
 [  33.4939995  -111.9174842 ]
 [  33.486037   -112.363428  ]
 [  33.39504586 -111.688385  ]
 [  33.710671   -112.202473  ]
 [  33.64032    -112.361552  ]
 [  33.413158   -111.875779  ]
 [  33.5

In [12]:
print(y_train)

[1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1
 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]


In [13]:
print(y_test)

[1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]


## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [15]:
print(X_train)

[[ 5.36987745e-02 -5.26942553e-01]
 [ 1.27321732e+00 -8.43623873e-01]
 [ 1.16435129e+00 -5.06071323e-01]
 [ 9.49231644e-01 -9.46056788e-01]
 [ 2.02580878e-01  3.17017963e-03]
 [-1.06164656e-02  5.29067694e-01]
 [ 5.17566730e-01 -1.67215300e+00]
 [ 1.05666839e+00  1.13283805e-01]
 [-1.17282916e+00  1.25938279e+00]
 [-3.13584235e-01 -1.34477815e-01]
 [-6.51263421e-01 -7.90018506e-01]
 [ 1.84003948e-01 -4.77521217e-01]
 [-2.33380657e-01 -6.07490335e-01]
 [-2.48994275e-01  4.27149069e-01]
 [ 6.33245812e-01 -8.64027289e-01]
 [-8.61578768e-01  5.17442058e-01]
 [ 2.08436442e-01 -5.50039721e-01]
 [ 2.51384535e+00  4.46005335e-01]
 [ 1.18205527e+00 -1.40320338e+00]
 [-7.57448181e-01  1.48571058e+00]
 [-4.29849386e-01  8.03192007e-01]
 [ 8.52657687e-01 -7.53694739e-01]
 [ 4.20246999e-01 -9.68572399e-01]
 [-1.00630271e+00 -3.21684234e+00]
 [ 1.27714765e+00 -9.64700245e-01]
 [ 1.33177150e+00 -1.16692308e+00]
 [ 9.06676423e-01 -2.49646277e-01]
 [ 7.26419102e-01  4.28104877e-01]
 [-1.07424792e+00  9

In [16]:
print(X_test)

[[ 1.15712433e+00  8.62661722e-02]
 [ 2.58368810e-01 -2.11140709e+00]
 [ 1.14811937e+00 -9.59990306e-01]
 [ 1.15265409e+00 -1.20281389e+00]
 [ 1.16398500e+00 -2.02885060e-01]
 [-7.54270953e-01 -4.45390041e-01]
 [ 1.16215060e+00 -7.50473855e-01]
 [ 1.62187520e-01 -4.25686817e-01]
 [ 1.91509136e+00  1.12085223e-01]
 [-9.80164022e-01  2.07769998e-01]
 [-1.69267552e+00  9.67386152e-01]
 [-6.58135083e-01  5.31116903e-01]
 [ 1.36634900e-01  4.42320918e-01]
 [ 1.16573735e+00 -4.31082271e-01]
 [-5.26640044e-02 -4.22448810e-01]
 [-4.41365149e+00  1.71256734e+00]
 [-9.67012628e-01  3.11384373e-01]
 [-2.97705288e-03 -6.92671616e-01]
 [ 1.66534967e+00 -1.69282059e+00]
 [ 2.18234055e-01 -8.46120104e-01]
 [-7.51355991e-01  4.10600073e-01]
 [ 1.24129647e-01  4.15143066e-01]
 [-1.29365818e-01 -2.21744370e+00]
 [-1.32346215e+00  9.41363464e-01]
 [-6.32375874e-01  5.31527845e-01]
 [ 3.41003843e-01 -4.20764068e-01]
 [ 9.46173973e-02  4.79149803e-01]
 [ 3.62851917e-02 -2.24789258e+00]
 [-6.30303679e-01  1

Training the Naive Bayes model on Training set

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

Training the Decision Tree model on Training set

In [20]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

Predicting the Test set result

In [21]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]]


Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)



[[ 2  6]
 [12 80]]
